<?php

/**
 * Implements hook_node_view().
 */
function tvkenya_show_node_view($node, $view_mode, $langcode) {
  switch ($node->type) {
    case 'show':
      switch ($view_mode) {
        case 'full':
          unset($node->content['links']['comment']);
//           unset($node->content['comments']);
//           $facebook_comments_block = module_invoke('facebook_comments', 'block_view', 'facebook-comments');
//           $node->content['fb_comments'] = array(
//             '#markup' => $facebook_comments_block['content']
//           );
          $node->content['navigation'] = array(
            '#markup' => _tvkenya_show_get_navigation($node),
//             '#weight' => 2222
          );
          break;

        default:
          break;
      }
      break;

    default:
      break;
  }
}

/**
 * Implements hook_field_extra_fields().
 */
function tvkenya_show_field_extra_fields() {
  $extra['node']['show'] = array(
    'display' => array(
      'fb_comments' => array(
        'label' => t('Facebook Comments'),
        'description' => t('Facebook Comments'),
        'weight' => 0,
      ),
      'navigation' => array(
        'label' => t('Navigation'),
        'description' => t('Navigation'),
        'weight' => 0,
      ),
    )
  );
  return $extra;
}

function _tvkenya_show_get_navigation($node) {
  $output = '<div class="show-navigation">';

  $q_previous = db_select('node', 'node_show');
  $q_previous->fields('node_show', array('nid', 'title'));
  $q_previous->fields('field_date', array('field_show_date_value', 'field_show_date_value2'));
  $q_previous->innerJoin('field_data_body', 'field_body', 'field_body.entity_id = node_show.nid');
  $q_previous->innerJoin('field_data_field_show_date', 'field_date', 'field_date.entity_id = node_show.nid');
  $q_previous->innerJoin('field_data_field_channel', 'field_channel', 'field_channel.entity_id = node_show.nid');
  $q_previous->condition('node_show.type', 'show');
  $q_previous->condition('field_body.bundle', 'show');
  $q_previous->condition('field_date.bundle', 'show');
  $q_previous->condition('field_channel.bundle', 'show');
  $q_previous->condition('field_channel.field_channel_target_id', $node->field_channel[LANGUAGE_NONE][0]['target_id']);
  $q_previous->condition('field_date.field_show_date_value', $node->field_show_date[LANGUAGE_NONE][0]['value'], '<');
  $q_previous->orderBy('field_date.field_show_date_value', 'DESC');
  $q_previous->range(0, 1);
  $previous = $q_previous->execute()->fetchObject();

  if ($previous) {
    $text = "<span class='title'>Prev: {$previous->title}</span>";
    $text .= "<span class='hour'>" . date("H:i", $previous->field_show_date_value) . ' - ' . date("H:i", $previous->field_show_date_value2) . "</span>";

    $output .= l($text, 'node/' . $previous->nid, array('html' => TRUE, 'attributes' => array('class' => array('navigation-item previous'))));
  }

  $q_next = db_select('node', 'node_show');
  $q_next->fields('node_show', array('nid', 'title'));
  $q_next->fields('field_date', array('field_show_date_value', 'field_show_date_value2'));
  $q_next->innerJoin('field_data_body', 'field_body', 'field_body.entity_id = node_show.nid');
  $q_next->innerJoin('field_data_field_show_date', 'field_date', 'field_date.entity_id = node_show.nid');
  $q_next->innerJoin('field_data_field_channel', 'field_channel', 'field_channel.entity_id = node_show.nid');
  $q_next->condition('node_show.type', 'show');
  $q_next->condition('field_body.bundle', 'show');
  $q_next->condition('field_date.bundle', 'show');
  $q_next->condition('field_channel.bundle', 'show');
  $q_next->condition('field_channel.field_channel_target_id', $node->field_channel[LANGUAGE_NONE][0]['target_id']);
  $q_next->condition('field_date.field_show_date_value', $node->field_show_date[LANGUAGE_NONE][0]['value'], '>');
  $q_next->orderBy('field_date.field_show_date_value', 'ASC');
  $q_next->range(0, 1);
  $next = $q_next->execute()->fetchObject();

  if ($next) {
    $text = "<span class='title'>Next: {$next->title}</span>";
    $text .= "<span class='hour'>" . date("H:i", $next->field_show_date_value) . ' - ' . date("H:i", $next->field_show_date_value2) . "</span>";

    $output .= l($text, 'node/' . $next->nid, array('html' => TRUE, 'attributes' => array('class' => array('navigation-item next'))));
  }

  $output .= '</div>';

  return $output;
}