<?php

/**
 * Implements hook_node_view().
 */
function tvkenya_show_node_view($node, $view_mode, $langcode) {
  switch ($node->type) {
    case 'show':
      switch ($view_mode) {
        case 'full':
          unset($node->content['links']['comment']);

          //  Add navigation.
          $node->content['navigation'] = array(
            '#markup' => _tvkenya_show_get_navigation($node),
          );

          //  Add social.
          $social_share_block = addtoany_block_view(0);
          $node->content['social_share'] = array(
            '#markup' => $social_share_block['content']
          );

          // Add ad.
          $ad_block = tvkenya_banner_block_view('right_banner');
          $node->content['ad'] = array(
            '#markup' => $ad_block['content']
          );
          break;

        default:
          break;
      }
      break;

    default:
      break;
  }
}

function _tvkenya_show_get_navigation($node) {
  $output = '<div class="show-navigation">';

  $q_previous = db_select('node', 'node_show');
  $q_previous->fields('node_show', array('nid', 'title'));
  $q_previous->fields('field_date', array('field_show_date_value', 'field_show_date_value2'));
  $q_previous->innerJoin('field_data_body', 'field_body', 'field_body.entity_id = node_show.nid');
  $q_previous->innerJoin('field_data_field_show_date', 'field_date', 'field_date.entity_id = node_show.nid');
  $q_previous->innerJoin('field_data_field_channel', 'field_channel', 'field_channel.entity_id = node_show.nid');
  $q_previous->condition('node_show.type', 'show');
  $q_previous->condition('field_body.bundle', 'show');
  $q_previous->condition('field_date.bundle', 'show');
  $q_previous->condition('field_channel.bundle', 'show');
  $q_previous->condition('field_channel.field_channel_target_id', $node->field_channel[LANGUAGE_NONE][0]['target_id']);
  $q_previous->condition('field_date.field_show_date_value', $node->field_show_date[LANGUAGE_NONE][0]['value'], '<');
  $q_previous->orderBy('field_date.field_show_date_value', 'DESC');
  $q_previous->range(0, 1);
  $previous = $q_previous->execute()->fetchObject();

  if ($previous) {
    $text = "<span class='title'>Prev: {$previous->title}</span>";
    $text .= "<span class='hour'>" . date("H:i", $previous->field_show_date_value) . ' - ' . date("H:i", $previous->field_show_date_value2) . "</span>";

    $output .= l($text, 'node/' . $previous->nid, array('html' => TRUE, 'attributes' => array('class' => array('navigation-item previous'))));
  }

  $q_next = db_select('node', 'node_show');
  $q_next->fields('node_show', array('nid', 'title'));
  $q_next->fields('field_date', array('field_show_date_value', 'field_show_date_value2'));
  $q_next->innerJoin('field_data_body', 'field_body', 'field_body.entity_id = node_show.nid');
  $q_next->innerJoin('field_data_field_show_date', 'field_date', 'field_date.entity_id = node_show.nid');
  $q_next->innerJoin('field_data_field_channel', 'field_channel', 'field_channel.entity_id = node_show.nid');
  $q_next->condition('node_show.type', 'show');
  $q_next->condition('field_body.bundle', 'show');
  $q_next->condition('field_date.bundle', 'show');
  $q_next->condition('field_channel.bundle', 'show');
  $q_next->condition('field_channel.field_channel_target_id', $node->field_channel[LANGUAGE_NONE][0]['target_id']);
  $q_next->condition('field_date.field_show_date_value', $node->field_show_date[LANGUAGE_NONE][0]['value'], '>');
  $q_next->orderBy('field_date.field_show_date_value', 'ASC');
  $q_next->range(0, 1);
  $next = $q_next->execute()->fetchObject();

  if ($next) {
    $text = "<span class='title'>Next: {$next->title}</span>";
    $text .= "<span class='hour'>" . date("H:i", $next->field_show_date_value) . ' - ' . date("H:i", $next->field_show_date_value2) . "</span>";

    $output .= l($text, 'node/' . $next->nid, array('html' => TRUE, 'attributes' => array('class' => array('navigation-item next'))));
  }

  $output .= '</div>';

  return $output;
}

/**
 * Theme show function for finder results.
 */
function tvkenya_show_finder_rewrite_result($row) {
  $output = NULL;
  $channel_nid = $row->node_field_data_field_channel_nid;

  // Set image.
  $image_data = $row->field_field_channel_image[0];
  $channel_image = theme_image_style(array(
    'style_name' => $image_data['rendered']['#image_style'],
    'height' => NULL,
    'width' => NULL,
    'path' => $image_data['raw']['uri']
  ));

  $show_title = l($row->node_title, 'node/' . $row->nid);
  $show_start_datetime = date('H:i', $row->field_field_show_date[0]['raw']['value']);
  if (date('j') == date('j', $row->field_field_show_date[0]['raw']['value'])) {
    $show_start_datetime = t('Today') . ' - ' . $show_start_datetime;
  }
  elseif (time() > $row->field_field_show_date[0]['raw']['value']) {
    $show_start_datetime = t('Yesterday') . ' - ' . $show_start_datetime;
  }
  elseif (time() < $row->field_field_show_date[0]['raw']['value']) {
    $show_start_datetime = t('Tomorrow') . ' - ' . $show_start_datetime;
  }

  $output =
<<<OUTPUT
  <div class="show-wrapper">
    <div class="channel" data-nid="{$channel_nid}">
      <a href="#channel-nid-{$channel_nid}">{$channel_image}</a>
    </div>
    <div class="show">
      <h3>{$show_title}</h3>
      <span class="date">{$show_start_datetime}</span>
    </div>
  </div>
OUTPUT;

  return $output;
}

/**
 * Implements hook_views_query_alter($view, $query).
 */
function tvkenya_show_views_query_alter($view, &$query) {
  if ($view->name == 'show_view_for_finder') {
    $url = $_SERVER['HTTP_REFERER'];
    $day = date('Y-m-d');
    if (strpos($url, 'schedule')) {
      $params = explode('schedule/', $url);
      switch ($params[count($params) - 1]) {
        case 'yesterday':
          $datetime = new DateTime('yesterday');
          $day = $datetime->format('Y-m-d');
          break;

        case 'tomorrow':
          $datetime = new DateTime('tomorrow');
          $day = $datetime->format('Y-m-d');
          break;

        case 'today':
        default:
          break;
      }
    }
    $query->where[1]['conditions'][2]['value'][':field_data_field_show_date_field_show_date_value'] = $day;
  }
}